repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v2.5.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements

  - repo: local
    hooks:
      - id: black
        name: black
        entry: black src tests
        language: system
        types: [python]
        args: [--skip-string-normalization]
        exclude: (notebooks/)

      - id: flake8
        name: flake8
        entry: flake8 --config=.code_quality/.flake8 src tests
        language: system
        types: [python]

      - id: pylint
        name: pylint
        entry: pylint --rcfile .code_quality/.pylintrc src tests
        language: system
        types: [python]

      #- id: pytest
      #  name: pytest
      #  language: system
      #  entry: pytest tests
      #  types: [python]
      #  pass_filenames: false

