name: Backport main to develop

on:

  push:
    branches:
      - main

permissions: write-all

jobs:

  backport:
    runs-on: ubuntu-latest

    steps:
    - name: GitHub Actions Runner
      uses: actions/checkout@v3.3.0

    - name: Create PR to sync main-develop
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GH_TOKEN }}
        branch: develop
        title: "[Backport] Sync main into develop at $(date +'%Y-%m-%d %H:%M:%S')"
        reviewers: daiha98
        labels: automated pr
        draft: false
