name: AI Shorts - Validation

on:

  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - develop

permissions: write-all

jobs:

  config:

    runs-on: ubuntu-latest
    steps:
    - name: GitHub Actions Runner
      uses: actions/checkout@v3.3.0
    - name: Setup SSH
      uses: MrSquaare/ssh-setup-action@v2
      with:
        host: github.com
        private-key: ${{ secrets.SSH_PRIVATE_KEY }}

  code_quality:

    runs-on: ubuntu-latest
    steps:
    - name: GitHub Actions Runner
      uses: actions/checkout@v3.3.0
    - name: Set ./src as PYTHONPATH
      run: |
        echo "PYTHONPATH=${{ github.workspace }}/src" >> $GITHUB_ENV
    - name: Install Dependencies
      run: |
        pip install -r requirements-dev.txt
    - name: Lint with Pylint/Flake8
      run: |
        pylint --rcfile .code_quality/.pylintrc src tests
        flake8 --config=.code_quality/.flake8 src tests
    - name: Unit tests with Pytest
      run: |
        pytest tests
