name: AI Shorts - CI-CD Pipeline

on:

  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - develop
      - main

permissions: write-all

env:

  PROJECT_NAME: "ai-shorts"

jobs:

  config:

    runs-on: ubuntu-latest
    steps:
    - name: GitHub Actions Runner
      uses: actions/checkout@v3.3.0
    - name: Setup SSH
      uses: MrSquaare/ssh-setup-action@v2
      with:
        host: github.com
        private-key: ${{ secrets.SSH_PRIVATE_KEY }}

  validate:

    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
    steps:
    - name: GitHub Actions Runner
      uses: actions/checkout@v3.3.0
    - name: Setup Python Version
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install Dependencies
      run: |
        pip install -r requirements-dev.txt
    - name: Lint with Pylint/Flake8
      run: |
        pylint --rcfile .code_quality/.pylintrc src tests
        flake8 --config=.code_quality/.flake8 src tests
